<?php

namespace AppBundle\Repository;

use AppBundle\Document\InvoiceStatus;
use AppBundle\Document\ServiceInfo;
use AppBundle\Document\ServiceStatus;
use Doctrine\ODM\MongoDB\DocumentRepository;
use Monolog\Logger;
use Monolog\Handler\StreamHandler;
/**
 * InvoiceHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvoiceHistoryRepository extends DocumentRepository
{
    

}