<?php

namespace AppBundle\Repository;

use AppBundle\Document\ServiceInfo;
use AppBundle\Document\ServiceStatus;
use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * ServiceInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceInfoRepository extends DocumentRepository
{
    public function findConfirmed($filters){

        $query = $this->createQueryBuilder()->field("isConfirmed")->equals(true);

        if($filters!=null){
            $query->field("status");
            if($filters['pending']=="true"){
                $query->addOr($query->expr()->field("status")->equals(ServiceStatus::Pendding));
            }
            if($filters['processing']=="true"){
                $query->addOr($query->expr()->field("status")->equals(ServiceStatus::Processing));
            }
            if($filters['completed']=="true"){
                $query->addOr($query->expr()->field("status")->equals(ServiceStatus::Completed));
            }
            if($filters['reviewed']=="true"){
                $query->addOr($query->expr()->field("status")->equals(ServiceStatus::Reviewed));
            }

        }
        //$query->field("status");
        //$query->addOr($query->expr()->field("status")->equals(ServiceStatus::Pendding));
        //$query->addOr($query->expr()->field("status")->equals(ServiceStatus::Reviewed));
        $serviceInfo = $query->sort(array("status"=>'ASC'))
            ->sort(array("serviceDate"=>'ASC'))
            ->getQuery()
            ->execute();

        return $serviceInfo;
    }

    public function findUnconfirmed(){

        $serviceInfo = $this->createQueryBuilder()
            ->field("status")->equals(ServiceStatus::Pendding)
            ->field("isConfirmed")->equals(false)
            ->sort(array("serviceDate"=>'ASC'))
            ->getQuery()
            ->execute();

        return $serviceInfo;
    }

    public function findPending($clientId){
        $activeClients = $this->findBy(array("status"=> ServiceStatus::Pendding,"clientId"=>$clientId));

        return $activeClients;
    }

    public function findCompleteService($clientId,$limit = 5){
        $query = $this->createQueryBuilder();

        $last = $this->createQueryBuilder()
            ->field("status")
            ->addOr($query->expr()->field("status")->equals(ServiceStatus::Completed))
            ->addOr($query->expr()->field("status")->equals(ServiceStatus::Reviewed))
            ->field("clientId")->equals($clientId)
            ->limit($limit)
            ->sort(array("serviceDate"=>'DESC'))
            ->getQuery()
            ->execute();
        return $last;
    }

    public function findLastCompleteService($clientId){

        $query = $this->createQueryBuilder();

        $last = $this->createQueryBuilder()
            ->field("status")
            ->addOr($query->expr()->field("status")->equals(ServiceStatus::Completed))
            ->addOr($query->expr()->field("status")->equals(ServiceStatus::Reviewed))
            ->field("clientId")->equals($clientId)
            ->limit(1)
            ->sort(array("serviceDate"=>'DESC'))
            ->getQuery()
            ->getSingleResult();
        return $last;
    }



    public function save($serviceInfo){
        $this->dm->persist($serviceInfo);
        $this->dm->flush();
    }

}